# Generated by Django 6.0.6 on 2026-06-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_photo_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Borrador'), (1, 'Emitida'), (2, 'Anulada')], default=0, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('total', 'Devolución Total'), ('parcial', 'Devolución Parcial')], default='total', max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('reason', models.CharField(max_length=300, verbose_name='Motivo')),
                ('is_active', models.BooleanField(default=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='billing.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
