# Generated by Django 6.0.6 on 2026-06-23 18:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_backfill_invoice_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Descuento (%)'),
        ),
    ]
