# Generated by Django 6.0.6 on 2026-06-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_product_tax_rate_invoicedetail_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/', verbose_name='Logo'),
        ),
    ]
