# Generated by Django 6.0.6 on 2026-06-23 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0007_product_tax_rate_invoicedetail_tax_amount'),
        ('purchasing', '0003_backfill_purchase_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('movement_type', models.CharField(choices=[('VENTA', 'Venta (Factura)'), ('DEV_VENTA', 'Devolución de Venta'), ('COMPRA', 'Compra'), ('DEV_COMPRA', 'Devolución de Compra'), ('ENT_MANUAL', 'Entrada Manual'), ('SAL_MANUAL', 'Salida Manual')], max_length=20, verbose_name='Tipo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='billing.invoice', verbose_name='Factura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='billing.product', verbose_name='Producto')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='purchasing.purchase', verbose_name='Compra')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-date'],
            },
        ),
    ]
