# Generated by Django 6.0.6 on 2026-06-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Borrador'), (1, 'Confirmada'), (2, 'Anulada')], default=0, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA'),
        ),
        migrations.CreateModel(
            name='SupplierCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('total', 'Devolución Total'), ('parcial', 'Devolución Parcial')], default='total', max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('reason', models.CharField(max_length=300, verbose_name='Motivo')),
                ('is_active', models.BooleanField(default=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='purchasing.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Nota de Crédito a Proveedor',
                'verbose_name_plural': 'Notas de Crédito a Proveedores',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
